@startuml
title Distant Profile Retrieval (Async)

actor "AppRequester" as AppRequester
participant "CommServ" as CommServer
actor "AppOwner" as AppOwner

AppRequester ->> CommServer : DistProfileRequest(Requester, RequestedUserUUID)
CommServer ->> AppOwner : FetchDistantProfile(Requester, RequestedUserUUID)
AppOwner ->> CommServer : DistProfileAnswer(Requester, RequestedUser)
CommServer ->> AppRequester : ForwardProfileAnswer(Requester, RequestedUser)

@enduml