@startuml
title Request Distant Profile (Client Initiation)

actor "UI" as UI
participant "Main" as Client
participant "CommCli" as CommClient
actor Server as S

UI ->> Client : demandProfile(RequestedUserUUID)
Client -> CommClient : requestDistProfile(RequestedUserUUID)
CommClient -> S : DistProfileRequestClient(Requester, AppOwner)
S --> CommClient : void
CommClient --> Client : void
Client --> UI : void

@enduml
