@startuml
title See Distant Profile (End-to-End Flow)

actor "UI" as UI
participant "Main" as Client
participant "CommCli" as CommClient
participant "DataCli" as DataClient
actor Server as S

UI -> Client : demandProfile(RequestedUserUUID)

Client -> CommClient : requestDistProfile(RequestedUserUUID)

CommClient -> S : DistProfileRequest(Requester, AppOwner)
S --> CommClient : void

CommClient -> DataClient : getDistantProfile()
DataClient --> CommClient : User


CommClient -> S : DistProfileAnswer(Requester, RequestedUser)


S -> CommClient : ForwardProfileAnswer(Requester, RequestedUser)


CommClient -> Client : DisplayDistProfile(RequestedUser)
Client --> UI : void

@enduml
