@startuml
title See Distant Profile 

actor "UI" as UI
participant "Main" as Client
participant "CommCli" as CommClient
actor Server as S

UI ->> Client : demandProfile(RequestedUserUUID)

Client -> CommClient : requestDistProfile(RequestedUserUUID)

CommClient ->> S : DistProfileRequest(Requester, AppOwner)
CommClient --> Client   : void

@enduml
