@startuml Close Kanban
actor Creator
participant "IHM – Kanban Client" as IHM
participant "Client Communication" as ClientCom
participant "Server Communication" as ServerCom

note over Creator: Close Kanban visualisation


Creator ->> IHM: Close Kanban visualisation (button)
IHM -> ClientCom: SendCloseKanban(lightKanban.id)
ClientCom ->> ServerCom: ForwardCloseKanban(lightUser.id, lightKanban.id)
ClientCom --> IHM: Give the execution thread to IHM-Kanban
note right of IHM: TODO: Transfer control back to IHM-Main
@enduml