name: Build Multi-OS

on:
  push:
    branches: ["main","ver/fin"]
  workflow_dispatch:

jobs:
  package-matrix:
    name: Package ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os-name: Windows
            extra-args: "--win-console"
          - os: ubuntu-latest
            os-name: Linux
            extra-args: ""
          - os: macos-latest
            os-name: MacOS
            extra-args: ""

    steps:
      - uses: actions/checkout@v4

      # Utilisation du cache Maven pour accélérer le setup
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Compilation sans les tests (plus rapide pour le packaging)
      - name: Build & Prepare
        shell: bash
        run: |
          mvn clean package dependency:copy-dependencies -DoutputDirectory=target/dist -DskipTests
          cp target/kanban-project-1.0-SNAPSHOT.jar target/dist/

      # Création Client
      - name: Package Client
        shell: bash
        run: |
          jpackage --name KanbanClient \
            --input target/dist \
            --main-jar kanban-project-1.0-SNAPSHOT.jar \
            --main-class client.MainApp \
            --type app-image \
            --dest dist-pkg \
            ${{ matrix.extra-args }}

      # Création Server
      - name: Package Server
        shell: bash
        run: |
          jpackage --name KanbanServer \
            --input target/dist \
            --main-jar kanban-project-1.0-SNAPSHOT.jar \
            --main-class server.ServerApp \
            --type app-image \
            --dest dist-pkg \
            ${{ matrix.extra-args }}

      # Upload des résultats
      - name: Upload ${{ matrix.os-name }} Apps
        uses: actions/upload-artifact@v4
        with:
          name: Kanban-${{ matrix.os-name }}
          path: dist-pkg