name: Build Linux Executables

on:
  push:
    branches: ["package_export", "main", "[vV][0-9]+"]

permissions:
  contents: read
  actions: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup and Build
        uses: ./.github/actions/setup-build

      - name: Package Client
        uses: ./.github/actions/package-artifact
        with:
          app-name: KanbanClient
          main-class: client.Launcher
          destination: dist_client
          artifact-name: KanbanClient-Linux
          artifact-path: dist_client/KanbanClient

      - name: Package Server
        uses: ./.github/actions/package-artifact
        with:
          app-name: KanbanServer
          main-class: server.ServerLauncher
          destination: dist_server
          artifact-name: KanbanServer-Linux
          artifact-path: dist_server/KanbanServer

      - name: Cleanup Old Artifacts
        uses: ./.github/actions/cleanup-artifacts
