name: Build Packages

on:
  push:
    branches: ["main", "[vV][0-9]+"]

permissions:
  contents: read
  actions: write

jobs:
  build-and-package:
    name: Build ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            java-arch: x64
            os-name: Windows
            extra-args: "--win-console"
            icon: ":desktop:"
          - os: ubuntu-latest
            java-arch: x64
            os-name: Linux
            extra-args: ""
            icon: ":penguin:"
          - os: macos-latest
            java-arch: aarch64
            os-name: MacOS
            extra-args: ""
            icon: ":apple:"

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-build
        with:
          java-architecture: ${{ matrix.java-arch }}

      - name: Package Client
        uses: ./.github/actions/package-artifact
        with:
          app-name: KanbanClient
          main-class: client.Launcher
          destination: dist
          extra-jpackage-args: ${{ matrix.extra-args }}

      - name: Package Server
        uses: ./.github/actions/package-artifact
        with:
          app-name: KanbanServer
          main-class: server.ServerLauncher
          destination: dist
          extra-jpackage-args: ${{ matrix.extra-args }}

      - name: Add MacOS Fix Script
        if: matrix.os-name == 'MacOS'
        run: |
          cat << 'EOF' > dist/fix_damaged_app.command
          #!/bin/bash
          DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
          echo "Fixing 'App is damaged' error..."
          sudo xattr -cr "$DIR/KanbanClient.app"
          sudo xattr -cr "$DIR/KanbanServer.app"
          echo "Done! You can now open the apps."
          EOF
          chmod +x dist/fix_damaged_app.command
        shell: bash

      - name: Upload ${{ matrix.os-name }} Bundle
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os-name }}-Kanban-Bundle
          path: dist

      - name: Notify Discord
        if: always()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "${{ matrix.icon }} Build ${{ job.status }}: ${{ matrix.os-name }}"
          embed-url: ${{ steps.upload-artifact.outputs.artifact-url }}
          embed-description: |
            **Branch:** `${{ github.ref_name }}`
            **Commit:** `${{ github.sha }}`

            :arrow_down: [Download Artifact](${{ steps.upload-artifact.outputs.artifact-url }})
          embed-color: ${{ job.status == 'success' && 5763719 || 15548997 }}
          embed-timestamp: ${{ github.event.head_commit.timestamp }}

      - name: Cleanup Old Artifacts
        uses: ./.github/actions/cleanup-artifacts
